title: 我的GitHub Pages
description: 个人网站
theme: minima

# 导航链接
nav:
  - title: 首页
    url: /
  - title: 关于
    url: /about
  - title: 项目
    url: /projects

# 基本设置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 作者信息
author:
  name: nds15763
  email: your.email@example.com

# 主题设置
logo: /assets/img/logo.png # 可以添加您的logo
show_downloads: false # 是否显示下载按钮
google_analytics: # 您的Google Analytics跟踪ID

# 其他设置
timezone: Asia/Shanghai
encoding: utf-8
