title: 我的GitHub Pages
description: 个人网站
theme: jekyll-theme-cayman

# 导航链接
nav:
  - title: 首页
    url: /
  - title: 关于
    url: /about
  - title: 项目
    url: /projects

# 基本设置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 作者信息
author:
  name: nds15763
  email: your.email@example.com

# 其他设置
timezone: Asia/Shanghai
encoding: utf-8
